### ISSUE TITLE
File Sidebar Icons 

### ISSUE THREAD

**Issue by nathggns** [oivva/boxy#100]
Unable to get sidebar icons for files to show up.

Here is my preferences file

```json
{
	"color_scheme": "Packages/User/SublimeLinter/Monokai (SL).tmTheme",
	"draw_white_space": "all",
	"fade_fold_buttons": false,
	"folder_exclude_patterns":
	[
		".svn",
		".git",
		".hg",
		"CVS",
		"node_modules",
		"bower_components"
	],
	"font_size": 14,
	"highlight_line": true,
	"line_padding_bottom": 6,
	"line_padding_top": 6,
	"scroll_past_end": false,
	"show_line_endings": true,
	"ignored_packages":
	[
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"theme": "Boxy Yesterday.sublime-theme",
	"color_scheme": "Packages/Boxy Theme/schemes/Boxy Yesterday.tmTheme",
	"theme_bar": true,
	"theme_bar_colored": true,
	"theme_button_inverted": true,
	"theme_button_rounded": true,
	"theme_find_panel_close_hidden": true,
	"theme_font_xl": true,
	"theme_icons_atomized": true,
	"theme_quick_panel_item_selected_colored": true,
	"theme_sidebar_border": false,
	"theme_sidebar_indent_top_level_disabled": true,
	"theme_size_xl": true,
	"theme_tab_arrows_hidden": true,
	"theme_tab_selected_filled": true,
	"theme_tab_selected_label_bold": true,
	"theme_tab_separator": true,
	"theme_tab_size_xl": true,
	"theme_sidebar_file_icons_hidden": false
}
```

And Here is the list of packages I have installed

* Alignment
* AngularJS
* AutoFileName
* Babel
* Boxy Theme
* Boxy Theme Addon - Linter Theme
* BracketHighlighter
* DocBlockr
* EditorConfig
* Emmet
* GitGutter
* Package Control
* Sass
* SideBarEnhancements
* SublimeLinter
* SublimeLinter-contrib-eslint
* SublimeLinter-jscs
* TypeScript

The icons appear for folders, but not for files.

**Comment by oivva** [comment]
Try to:

1. Remove: `"theme_sidebar_file_icons_hidden": false` from your preferences.
2. Restart Sublime Text

  - [macOS]   `Sublime Text -> Quit Sublime Text`
  - [Windows] `File -> Exit`
  - [Linux]   `File -> Exit`

**Comment by oivva** [comment]
If only some icons are missing, try to remove other custom themes. More details [here](https://forum.sublimetext.com/t/sublime-text-3-file-icons-in-sidebar/21134/4).

**Comment by rolandba** [comment]
I hae the same issue. Restart was not helpfull. The icons appear for folders, but not for files.

**Comment by oivva** [comment]
Ah, sorry! It seems I found the solution, v3.1.1 will be available soon.

**Comment by oivva** [comment]
Done, will be available soon on Package Control. Sorry for the inconvenience :disappointed:
