### ISSUE TITLE
TypeScript popup theming

### ISSUE THREAD

**Issue by nathggns** [oivva/boxy#103]
There seems to be an issue with the theming of TypeScript popups as you can see in the image below.

![image](https://cloud.githubusercontent.com/assets/719814/17248869/2333de48-5595-11e6-88dd-e45bd31db889.png)

This is my theme settings 

```json
{
	"color_scheme": "Packages/Boxy Theme/schemes/Boxy Yesterday.tmTheme",
	"theme": "Boxy Yesterday.sublime-theme",
	"theme_bar": true,
	"theme_bar_colored": true,
	"theme_button_inverted": true,
	"theme_button_rounded": true,
	"theme_find_panel_close_hidden": true,
	"theme_font_xl": true,
	"theme_icons_atomized": true,
	"theme_quick_panel_item_selected_colored": true,
	"theme_sidebar_border": false,
	"theme_sidebar_file_icons_hidden": false,
	"theme_sidebar_indent_top_level_disabled": true,
	"theme_size_xl": true,
	"theme_tab_arrows_hidden": true,
	"theme_tab_selected_filled": true,
	"theme_tab_selected_label_bold": true,
	"theme_tab_separator": true,
	"theme_tab_size_xl": true
}
```

**Comment by oivva** [comment]
It seems TypeScript popup colors are hardcoded. 

Related to [this](https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/498).

**Comment by oivva** [comment]
Will be available in the next release. After closing: https://github.com/Microsoft/TypeScript-Sublime-Plugin/pull/511
