### ISSUE TITLE
output panel margin too narrow

### ISSUE THREAD

**Issue by randy3k** [oivva/boxy#104]
output panel margin too narrow

<img width="357" alt="screen shot 2016-07-29 at 2 05 41 pm" src="https://cloud.githubusercontent.com/assets/1690993/17258569/8f06f5b0-5595-11e6-8f07-3552df67d57f.png">

Compare to the original theme.

<img width="332" alt="screen shot 2016-07-29 at 2 04 50 pm" src="https://cloud.githubusercontent.com/assets/1690993/17258541/6ff48b42-5595-11e6-9685-928b4d4d54e9.png">

#### Your Environment

```json
	"theme": "Boxy Monokai.sublime-theme",
	"theme_accent_lime": true,
	"theme_bar": true,
	"theme_bar_logo_atomized": true,
	"theme_button_inverted": true,
	"theme_button_rounded": true,
	"theme_dropdown_atomized": true,
	"theme_find_panel_atomized": true,
	"theme_find_panel_close_hidden": true,
	"theme_find_panel_size_xs": true,
	"theme_icon_button_highlighted": true,
	"theme_icons_atomized": true,
	"theme_panel_switcher_atomized": true,
	"theme_quick_panel_item_selected_colored": true,
	"theme_scrollbar_colored": true,
	"theme_scrollbar_line": true,
	"theme_sidebar_indent_top_level_disabled": true,
	"theme_tab_selected_label_bold": true,
	"theme_tab_selected_transparent": true,
	"theme_tab_selected_underlined": true,
	"theme_tab_separator": true,
	"theme_tab_size_xl": true,
```

Boxy 3.1.1
Sublime Text 3 3114
Mac OS 10.11

**Comment by oivva** [comment]
Ok, I'll add some options in the next release.
