### ISSUE TITLE
Dirty Accents?

### ISSUE THREAD

**Issue by facelessuser** [oivva/boxy#105]
I like Boxy, but there is one thing I've really wanted that isn't available, and that is dirty accent colors.  I the dirty indicators are fine, but often I have to really look.  I would love to have the option  to set any of the other possible accent colors to the dirty indicator.  So maybe if I am using a blue theme, I could set my dirty indicator to red, or whatever I think stands out to me.

**Comment by oivva** [comment]
OK, I'll add option to change accent of the dirty icon in the 4.0.0.

**Comment by facelessuser** [comment]
Works great.  Thanks for taking the time 👍 .
