### ISSUE TITLE
3.2.X FAQ

### ISSUE THREAD

**Issue by oivva** [oivva/boxy#106]
Starting 3.2.0 you can use a bunch of stuff that lets you quickly customize many aspects of the Sublime Text UI. But now the theme requires next [dependencies](https://github.com/oivva/boxy/blob/dev/dependencies.json) which may cause some issues.

After updating:

1. Open `Command Palette` using menu item `Tools → Command Palette...`
2. Choose `Package Control: Satisfy Dependencies`
3. Restart Sublime Text
    * **macOS** : menu item `Sublime Text -> Quit Sublime Text`
    * **Windows**: menu item `File -> Exit`
    * **Linux** : menu item `File -> Exit`

If you still see some errors in the console try:

1. Open `Command Palette` using menu item `Tools → Command Palette...`
2. Choose `Package Control: Browse Packages`
3. Exit Sublime Text
4. Remove folders
    * `markupsafe`
    * `mdpopups`
    * `pygments`
    * `python-jinja2`
    * `python-markdown`
5. Start Sublime Text
6. Open `Command Palette` using menu item `Tools → Command Palette...`
7. Choose `Package Control: Satisfy Dependencies`
8. Restart Sublime Text
    * **macOS** : menu item `Sublime Text -> Quit Sublime Text`
    * **Windows**: menu item `File -> Exit`
    * **Linux** : menu item `File -> Exit`

**Comment by the1900** [comment]
- OS Windows 7 x32
- Boxy Theme: 3.2.0
- Sublime Text: 3114
- Platform: windows
- Package Control: True
- Dependencies:
	* mdpopups: 1.9.3
	* markdown: 2.6.6
	* pygments: 2.1a0
	* jinja2: 2.8

@oivva  If you don't mind I wonder how to display icons in configurator panel

![1](https://cloud.githubusercontent.com/assets/10105141/17481631/25535c54-5db9-11e6-9fbc-baf0af2f93d4.png)


My font face on user setting is Consolas

**Comment by AlfonzM** [comment]
@oivva How do I disable the cmd+` shortcut to open the config panel? It's overriding the macOS shortcut to cycle through application windows, which I use a lot. Thanks.

**Comment by oivva** [comment]
@AlfonzM Oh, sorry. I'm not macOS user. I'll remove shortcut by default. If someone wants to run configurator via shortcut he should add this into his `User Key Bindings`:

```json
{
    "keys": ["<shortcut>"],
    "command": "boxy_config"
}
```

**Comment by oivva** [comment]
@the1900 Hmm, very strange. It works for me on Windows 7, but I have updated Consolas font to the higher version as yours. You can try override `Consolas` with [these fonts](http://radiokot.ru/forum/download/file.php?id=193874&sid=2ae21dcc20459aa2a59d6e7766017cb7).

**Comment by the1900** [comment]
@oivva Thanks for give me files. But I'm afraid, It is still doesn't show.
The one thing strange this is In my Win10 it says your font file version is 5.2.2 besides In Win 7 it is 5.3.3 what weird right?

**Comment by oivva** [comment]
@the1900 I gave you the font files that I'm using. Consolas versions: https://www.microsoft.com/typography/fonts/font.aspx?FMID=1924. I don't know which is the right, but the latest version includes those symbols for sure. Are you facing the same issue on Windows 10?

**Comment by robinbentley** [comment]
Is there a way to disable the super+` keybind for the config panel whilst you're working on making optional? Cheers

**Comment by the1900** [comment]
@oivva  Nope only windows 7 is problem. there are same version of stable and portable version (x86)

**Comment by oivva** [comment]
@robinbentley It's already disabled. 3.2.1 will be updated soon via Package Control.

**Comment by oivva** [comment]
@the1900 All that I can say that's the font issue, because your version of the font doesn't include those symbols. Possible solutions:
* Update `Consolas`, you can simply copy your fonts from `Windows 10` to `Windows 7`
* Copy custom version of the [configurator](https://github.com/oivva/boxy/blob/dev/boxy_config.py) to the `User` folder (which you can find in `Preferences -> Browse Packages`)

You need to change these values:

```py
MARKED = '✓'
UNMARKED = '✗'
RADIO_MARKED = '☒'
RADIO_UNMARKED = '☐'
```

**Comment by oivva** [comment]
3.2.1 is available via Package Control.

Forcing the upgrade:

1. Open `Command Palette` using menu item `Tools → Command Palette...`
2. Choose `Package Control: Upgrade Package`
3. Find `Boxy Theme`
4. Hit `Enter`

**Comment by the1900** [comment]
@oivva It is kind of you! 
well I literally copied you gave It still doesn't work.
Thanks for detailed explanation to replace it.

**Comment by the1900** [comment]
@oivva  I guess that unicodes aren't contain in Consolas

![004](https://cloud.githubusercontent.com/assets/10105141/17489861/1902710c-5ddb-11e6-801e-872658657aa4.png)

You can see there is no check mark in the Consolas. This viewer is default windows viewer

**Comment by oivva** [comment]
> It was your fallback font.
Ah, it's clear now :wink:

**Comment by oivva** [comment]
[`mdpopups`](https://github.com/facelessuser/sublime-markdown-popups/releases) dependency was recently updated. I've prepared support of it. 

Please run `Package Control: Satisfy Dependencies` after the update to 3.2.2 and restart ST.

**Comment by oivva** [comment]
I think Boxy is pretty stable, so I hope we won't have any `hotfixes` in the near future. Your workflow is safe :wink:

**Comment by oivva** [comment]
@the1900 Starting 3.2.2 you can change the symbol icons of the configurator by modifying your user preferences file:

```json
"theme_config_marked": "✓",
"theme_config_unmarked": "✗",
"theme_config_radio_marked": "☒",
"theme_config_radio_unmarked": "☐",
```

**Comment by the1900** [comment]
@oivva  I am touched by your concern.
That is totally solution of this problem. Thanks :) 

BTW I'm looking for Windows font configuration to response all kind of this situation. 
It is little bit complicated but It's possible to adjust primary font, secondary font, etc by editing registry manually. See [Font linking](https://msdn.microsoft.com/en-us/library/ee489864.aspx)
