### ISSUE TITLE
Python file type icon enhancement

### ISSUE THREAD

**Issue by bofm** [oivva/boxy#111]
It would be grateful if Python file type icon was modified to make its upper part blue like below.
![Python logo](http://www.iconarchive.com/download/i73027/cornmanthe3rd/plex/Other-python.ico).

The current one (![icon](https://github.com/oivva/boxy/raw/ab64d4a6a25ae62d73eb2e5e5117012b7abb4ae7/icons/file_type_python.png)) doesn't look pythonic.

I am sorry for such a minor enhancement request. Perfect theme deserves perfect icons.

**Comment by oivva** [comment]
No problem :wink:

**Comment by oivva** [comment]
Some users don't like the new Python icon. That's why we are creating a poll.

![](https://raw.githubusercontent.com/oivva/boxy/dev/icons/file_type_python.png) :+1:

![](https://raw.githubusercontent.com/oivva/boxy/v3.2.4/icons/file_type_python.png) :-1:

**Comment by oivva** [comment]
Some users don't like the new Python icon. That's why we are creating a poll.

![](https://raw.githubusercontent.com/oivva/boxy/dev/icons/file_type_python.png) :+1:

![](https://raw.githubusercontent.com/oivva/boxy/v3.2.4/icons/file_type_python.png) :-1: 

> The poll will close September 17, 2016

**Comment by ArtemBernatskyy** [comment]
Dislike new icon, with blue colors it looks awful. I vote for completely yellow.

**Comment by bofm** [comment]
Awful or not the new one looks similar to the official Python language logo. As Boxy uses combinatins of orange and neon-blue colors of the icons by default, it is reasonable to make Python icon similar to the official logo and preserve the colours of the theme.

**Comment by michaelblyons** [comment]
While I do not think that the new colors are "awful," I think there is something to be said for all of the icons being single-color.

**Comment by oivva** [comment]
@michaelblyons @bofm @ArtemBernatskyy I jumped a little fast with icon update. Yes, all theme icons are single-color, latest update make `python icon` a little special in comparison with other icons. In this case we need to review all icons, but I don't have time to provide alternatives. That's why I return previous icon in the next release.

**Comment by oivva** [comment]
@bofm @ArtemBernatskyy Note, you can override icon manually via copying:
`file_type_python.png`, `file_type_python@2x.png`, `file_type_python@3x.png` to `Theme - Default` folder which you can find by menu item `Preferences -> Browse Packages`.

**Comment by bofm** [comment]
> Note, you can override icon manually...

@oivva Yeah, no problem. It can also be done by putting custom icons to `Packages/User/Boxy Theme/icons/`.

**Comment by oivva** [comment]
@bofm Yes, but Sublime Text removes this folder on each theme update, doesn't it?

**Comment by bofm** [comment]
@oivva It doesn't delete `Packages/User/*` on package updates unless a package is designed to do it.
