### ISSUE TITLE
Ugrade too frequently

### ISSUE THREAD

**Issue by yutent** [oivva/boxy#113]
It always breaks my work.
Can add a config filed to close "auto upgrade" ?

**Comment by oivva** [comment]
This is the default way of updating the current theme (see [this](https://forum.sublimetext.com/t/more-elegant-way-of-updating-the-current-theme/22174)).

However you can customize these options in your `Package Control - User Settings` (menu item: `Preferences -> Package Settings -> Package Control -> Settings - User`):

```js
// The minimum frequency in hours in which to check for automatic upgrades,
// setting this to 0 will always check for automatic upgrades
"auto_upgrade_frequency": 1,

// Packages to not auto upgrade
"auto_upgrade_ignore": [],
```
