### ISSUE TITLE
Add extra small variant of the find & replace panel

### ISSUE THREAD

**Issue by oivva** [oivva/boxy#114]
Details: https://forum.sublimetext.com/t/boxy-the-most-hackable-theme-for-sublime-text-3/20564/64

**Comment by AhmadQatar** [comment]
hi,
i'm using "Boxy Tomorrow".

Check attach please , i want know how to set more height for tabs ?

thanks
![boxy](https://cloud.githubusercontent.com/assets/3172428/18025756/0b117ce0-6c3c-11e6-8f15-8f9f91ec1381.png)

**Comment by oivva** [comment]
@AhmadQatar Hi, see: https://github.com/oivva/boxy/wiki/Settings#tab-size

```js
// Increase size of tabs to extra large
"theme_tab_size_xl": true,
```

**Comment by AhmadQatar** [comment]
good, but still small 
I hope that there will be an option to put number

thanks.

:+1:

**Comment by oivva** [comment]
> I hope that there will be an option to put number

@AhmadQatar Sorry, it's hard to implement that. You can try to change it manually via `PackageResourceViewer` or tell me the height value and I'll add `theme_tab_size_xxl` option.

**Comment by AhmadQatar** [comment]
That would be great :+1: 
I think the size of the rise would be better if it was 55 like "material theme"

Thanks
