### ISSUE TITLE
Can not install with ST 3114

### ISSUE THREAD

**Issue by kvokka** [oivva/boxy#115]
If I install with PC, I have no any items in menu, with PC Satisfy Dependencies it start download only 1 dependency on each boot.

If I install it manually, it is shown in the main menu, install dependencies but still not activated, in PC there is no "Boxy".

Shell I roolback ST, or it is known issue, or etc? (I did not fount mansion about mine situation in closed issues)

Thank you!

**Comment by oivva** [comment]
Please try:
0. Uninstall theme
1. Open `Packages` folder (via menu item `Sublime Text → Preferences → Browse Packages ...`)
2. Quit Sublime Text
    - **macOS** : menu item `Sublime Text → Quit Sublime Text`
    - **Windows**: menu item `File → Exit`
    - **Linux** : menu item `File → Exit`
3. Remove next directories from `Packages`:
    - `mdpopups`
    - `python-markdown`
    - ``
    - ``

**Comment by kvokka** [comment]
Thank you for so soon answer.
I've already done it twice. Also, I want to say, that i've downloaded dependencies 1-by-1, cause PC: Satisfy Dependencies fetch only 1 dependency in 1 request (I do not know, is it reasonable behavior).

I've tried with deletion Cache, Local  Backup folders + clean up /Packages

Now I achive that I have all installed dependencies, I have all inactive items with boxy in Package Settings -> Boxy Theme
+ have no boxy in PC menu. I do not know what else to I can to do.

**Comment by oivva** [comment]
@kvokka Sorry, see updated comment :smile: I don't recommend you install it manually, I think you have problem with `0_package_control_loader.sublime-package-new` (PC hasn't done it work, that's why you see problems with dependency installation on each boot).

**Comment by oivva** [comment]
If [this steps](https://github.com/oivva/boxy/issues/115#issuecomment-243659850) didn't help you, please provide your OS details. I'll try to find the solution.

P.S. It works for me with ST3114.

**Comment by kvokka** [comment]
I've alived it :)
The problem was in package control. I remove package control (leaved packages & settings) and setup it back. It helps. I do not know, why does it happens, but, it helps. May be this information will be useful for somebody

Thank you for your time and cooperation!
