### ISSUE TITLE
Quick panel changes

### ISSUE THREAD

**Issue by leemet** [oivva/boxy#29]
Hi there,

Just want to say awesome theme so far, it's replaced predawn for me.

One feature I'd love to see brought across would be a smaller quick panel, as in the padding between each element, made smaller so more files can be accessed. I use sublime SFTP to access remote servers and it's done through this panel, so having as much space as possible in here to allow more files to be visible makes a massive difference.

Otto panel : 
![quick panel](https://cloud.githubusercontent.com/assets/8605625/13753546/4ae9ca88-ea0b-11e5-8f0b-e86ccb027d82.png)

Predawn panel : 
![small quick panel](https://cloud.githubusercontent.com/assets/8605625/13753556/533f7bd8-ea0b-11e5-975f-c51aaf45a8d8.png)

Also, is it possible to make this panel taller? I could never figure it out.

Thanks again. #

**Comment by oivva** [comment]
Thanks for reporting the issue.  I'll add configuration settings in the next release.
