### ISSUE TITLE
[Request] Add option to display comment in italic

### ISSUE THREAD

**Issue by redgluten** [oivva/boxy#36]
I think the defaults to not use italics are good because no one wants to have [faux-italics](http://www.marksimonson.com/notebook/view/FakevsTrueItalics) (urk), but there are [some](http://www.typography.com/fonts/operator/overview/) programming fonts that propose great italics. I think they are especially nice for comments. Would it be possible to add such an option? I’m willing to make a pull-request if you can point me to the resources explaining how we can do that because I was unable to find them. :)

P.S: thanks for the awesome work put in this theme, I like it a lot. 👍

**Comment by oivva** [comment]
Thanks for your request. I'll add this option in the next major release.
