### ISSUE TITLE
New File input bar obscured by bottom message panel

### ISSUE THREAD

**Issue by HopefulLlama** [oivva/boxy#40]
If Sublime is currently displaying a message in the bottom panel (in this example, the message shown by the add-on package Sublimerge), the new file prompt is covered by it.

This is as shown in the image.

![wrong](https://cloud.githubusercontent.com/assets/6244529/15324096/efd740bc-1c3c-11e6-80f2-44a51978e0d7.png)

**Comment by oivva** [comment]
Look at [Known Issues](https://github.com/oivva/boxy#known-issues) section
Just drag the top edge and restart Sublime Text.

**Comment by HopefulLlama** [comment]
I didn't realise you could drag other panels too!

My apologies then, feel free to close this issue.

**Comment by oivva** [comment]
:wink:
