### ISSUE TITLE
New accents

### ISSUE THREAD

**Issue by oivva** [oivva/boxy#44]
I have plans to review orange accent and add more new accents in the next release. Please post your suggestions :wink:

**Comment by TONTRI-TECH** [comment]
Go Ahead and add orange, sky blue and pink accents :)

**Comment by eproxus** [comment]
I'd like some darker accent colors, for using the `"theme_bar": true` setting without getting blinded when using a dark theme (like Boxy Tomorrow). :smile: A grey/dark grey color would be awesome.

**Comment by alexwhitman** [comment]
Seconding a dark highlight.  Something similar to Gravity would be nice: https://github.com/frankyonnetti/gravity-sublime-theme

**Comment by christopherdwhite** [comment]
A couple of mono-chrome access would be great, maybe a white, a black and a dark grey?

I would also love a setting to override the accent on sidebar folders, I find them a little distracting when using the (gorgeous) light Yesterday theme.

**Comment by oivva** [comment]
> I would also love a setting to override the accent on sidebar folders, I find them a little distracting when using the (gorgeous) light Yesterday theme.

Thanks, completely agree with you. I have plans to implement this settings and monochrome icons in 2.1.0.

**Comment by oivva** [comment]
@christopherdwhite

> I would also love a setting to override the accent on sidebar folders
Starting 2.0.2 you can use:

```js
theme_sidebar_folder_monochrome: true,
```

**Comment by eproxus** [comment]
It's not related to accents per se, but I would like to see the `"theme_bar": true` setting getting a complementary `"theme_bar_dark": true` setting or similar. I like the new and improved bar, but it is way too bright with the accent color as the background.

**Comment by oivva** [comment]
> It's not related to accents per se, but I would like to see the `"theme_bar": true` setting getting a complementary `"theme_bar_dark": true` setting or similar.

Thanks, I have plans to implement this as you describe, not only via changing accent at all.

**Comment by jpcharrier** [comment]
Love love love this theme...!! Can I put a request in to expand the colour syntax? I have a few favs that I would love to add in... 

Something similar to Material Darker
![screen shot 2016-06-09 at 12 43 00 pm](https://cloud.githubusercontent.com/assets/1574534/15915733/f0185b00-2e3f-11e6-9b32-6aed394b30ea.png)

Something similar to Peacock (SL)
![screen shot 2016-06-09 at 12 44 17 pm](https://cloud.githubusercontent.com/assets/1574534/15915741/f99a7ff0-2e3f-11e6-959c-f3dc30c4b1ff.png)


Perhaps I should open a new issue for this 👍  – I'd also be happy to help port these accross (just a little unsure on process - sorry bit of a n00b with contributing).

**Comment by oivva** [comment]
@jpcharrier, thanks for your request. Sorry, I have no time and plans to maintain more themes. But I can help you if you want to create fork with more themes (something similar to [Materialize](https://github.com/saadq/Materialize) for [Material Theme](https://github.com/equinusocio/material-theme)).

> Something similar to Material Darker
As far as I can see starting [3.0.0](https://github.com/equinusocio/material-theme/tree/release/v3.0.0/), Material Theme will be use some parts of the Boxy builder, so maybe some missing features for you will be available later in it.

**Comment by oivva** [comment]
![accents](https://cloud.githubusercontent.com/assets/9801624/16090124/e4f44c24-3336-11e6-8f62-0f378e86a32f.png)

**Comment by Vercoutere** [comment]
Gold/Amber/Yellow would be cool.

**Comment by oivva** [comment]
@Vercoutere Thanks, maybe in the future releases, for 3.0.0 it will be more than enough.

**Comment by oivva** [comment]
Sorry, mono accent won't be added due to it's difficult implementation (it needs too many styles to override & yeah, all themes already have more than 10k lines of code).

However I added other good improvements and features (including mono top bar), you can test them out by installing dev branch manually and of course they will be available in the next release.

**Comment by oivva** [comment]
"azure" will be named as `sky`
