### ISSUE TITLE
Color scheme support for invalid.illegal

### ISSUE THREAD

**Issue by michaelblyons** [oivva/boxy#46]
Sublime Text has a scope for illegal characters in certain contexts. Can you add "angry" colors for `invalid` or `invalid.illegal`? It seems typical to use white for the foreground and a color-scheme-appropriate red for the background.

Try the following code with the Javascript syntax in Monokai:

```js
var foo = "asdf
var bar;
```

**Comment by oivva** [comment]
Thanks for reporting the issue. I'll fix it just a little bit later today.
