### ISSUE TITLE
File icons not displaying in sidebar

### ISSUE THREAD

**Issue by JoeArizona** [oivva/boxy#47]
Hi Ihor – I installed boxy in Sublime Text 3, build 3114 (Windows 10) but I don't see any file icons in the sidebar. Do I need to do anything in particular? I used your recommended config. I'm not sure I even know how to get a sidebar that shows all the contents of a directory like in your screenshots. In Sublime, the only option I see is View --> Sidebar --> Show Open Files, and when I do that I see my open files, but no file icons for them (e.g. I have HTML, JS, and YAML files open.)

Thanks,

Joe

**Comment by oivva** [comment]
Hi! Can you show your full user settings? 

> I'm not sure I even know how to get a sidebar that shows all the contents of a directory like in your screenshots.

If you want to see the contents of a directory, you should open it in Sublime Text (**`File → Open Folder...`**) or add the directory to the project (**`Project → Add Folder to Project`**).

> In Sublime, the only option I see is View --> Sidebar --> Show Open Files, and when I do that I see my open files, but no file icons for them (e.g. I have HTML, JS, and YAML files open.)

Unfortunately, Sublime Text doesn't support icons for open files. Vote for this [issue](https://forum.sublimetext.com/t/icons-in-sidebar-for-open-files/19917).

**Comment by JoeArizona** [comment]
Thanks Ihor, your tip about Project → Add Folder to Project fixed it!

File → Open Folder annoys me because it opens a new Sublime window. Apparently, the setting to disable this only works on Macs.

For the record, here are my user settings, but it's fixed now:

{
	"always_show_minimap_viewport": true,
	"auto_complete_size_limit": 2096,
	"bold_folder_labels": true,
	"caret_extra_bottom": 1,
	"caret_extra_top": 1,
	"caret_extra_width": 1,
	"caret_style": "blink",
	"default_line_ending": "unix",
	"ensure_newline_at_eof_on_save": true,
	"fade_fold_buttons": false,
	"font_face": "Roboto Mono",
	"font_options":
	[
		"directwrite",
		"subpixel_antialias"
	],
	"font_size": 11,
	"highlight_modified_tabs": true,
	"ignored_packages":
	[
		"C",
		"CSS",
		"Python",
		"RestructuredText",
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"line_padding_bottom": 1,
	"line_padding_top": 1,
	"open_files_in_new_window": false,
	"overlay_scroll_bars": "enabled",
	"scroll_past_end": false,
	"shift_tab_unindent": true,
	"show_encoding": true,
	"show_line_endings": true,
	"word_wrap": "true",
	"theme": "Boxy Ocean.sublime-theme",
	"theme_sidebar_file_icons_hidden": false,
	"color_scheme": "Packages/Boxy Theme/schemes/Boxy Ocean.tmTheme"
}

**Comment by JoeArizona** [comment]
By the way, there was apparently an update to the theme today that knocked it out. Sublime had a popup that said that the theme had been updated and that I might need to restart Sublime. For some reason it reverted the theme in User Settings to the default Sublime theme, and I had to go in and replace it with Boxy Ocean.sublime-theme.

**Comment by oivva** [comment]
> For some reason it reverted the theme in User Settings

Hmm, very strange behavior. It should reactivate theme after each update, try just restart Sublime Text after each update.
