### ISSUE TITLE
UI font face can't be changed

### ISSUE THREAD

**Issue by toph-allen** [oivva/boxy#50]
In previous versions of Boxy it was possible to change the UI font face through the hacky method of editing "font.face" attributes in the .tmTheme files. This doesn't seem to be possible any more, though. Is this ability coming back somehow?

**Comment by oivva** [comment]
Sorry for the regression. I'll add this settings back in the next release.

**Comment by oivva** [comment]
@toph-allen Done, look at [addons](https://github.com/search?q=user%3Aoivva+boxy-addon).

**Comment by toph-allen** [comment]
Nicely done!
