### ISSUE TITLE
Review file type icons

### ISSUE THREAD

**Issue by oivva** [oivva/boxy#54]

**Comment by gerardroche** [comment]
Would be nice to to have option for black and white icons and also an option to have github octicon icons. 


![96e416e8-da24-11e4-995c-00dcd84c276d](https://cloud.githubusercontent.com/assets/44148/8639658/e73daf8e-28d8-11e5-82eb-e89e7bf56358.png)

See Atom One Dark UI https://github.com/atom/one-dark-ui
See Icons used by Atom One Dark UI https://atom.io/packages/file-icons
See Github Octicons https://octicons.github.com/

See also Material Theme issue: https://github.com/equinusocio/material-theme/issues/324

**Comment by oivva** [comment]
> Black and white icons

It will be available soon, in 2.1.0 :wink: 

> Icons used by Atom One Dark UI 

I like this icons :+1: I'll add them via options later.

> Github Octicons

Can you explain in such cases they should be displayed?

> Material Theme

I have some ideas, and yes it's possible to add another set of icons.

**Comment by oivva** [comment]
After some work on this issue, I can say that

> Icons used by Atom One Dark UI https://atom.io/packages/file-icons

won't be added as is, because default icons will be pretty similar to those ones (imo in some cases they will be better, in other cases they will be the same).

**Comment by oivva** [comment]
> Some are very similar. Some of the atom icons tend be a little better e.g. json, ruby, php, markdown.
OK. Wait 3.0.0, I think you'll be satisfied :wink: I hope it's will be available this week.

**Comment by nanalan** [comment]
I'm also having a problem with the `svg` icon - there's nothing there!
![image](https://cloud.githubusercontent.com/assets/9429556/16609620/65d2b512-434d-11e6-9420-f86a01b1f012.png)

**Comment by oivva** [comment]
It will be fixed in 3.0.0

**Comment by oivva** [comment]
@nanalan I have some info for you. With 2.x.x you should see markup icon for svg. For that you should remove other custom UI themes (Material Theme, Seti & etc) because of preferences conflict. This is sad, but currently you should choose only one custom theme for daily use and remove others. More info here: https://forum.sublimetext.com/t/sublime-text-3-file-icons-in-sidebar/21134/4
