### ISSUE TITLE
Sidebar indent & spacing

### ISSUE THREAD

**Issue by Lugoues** [oivva/boxy#57]
I was thinking of putting a pull request in to make the sidebar size settings include smaller indent & vertical padding. Do you think I should just put this into theme_sidebar_size_xxx options, or make new options for indent and vertical padding?

**Comment by oivva** [comment]
@Lugoues

> smaller indent

If you want to tweak this properties

```js
// Sidebar Tree Defaults
// ---------------------------------------------------------------------------

{
  "class": "sidebar_tree",
  "row_padding": [20, 6, 20, 5],
  "indent": 10,
  "indent_offset": -8,
  "indent_top_level": true, // As variant to turn off this option
  "layer0.opacity": 1.0
},
```

It would be better to add new options, something like `theme_sidebar_indent_xx`.

> vertical padding

Can you explain me how it differs from

```js
{
  "class": "sidebar_tree",
  "settings": ["theme_sidebar_size_xs"],
  "row_padding": [20, 5, 20, 4]
},

{
  "class": "tree_row",
  "settings": ["theme_sidebar_size_xs"],
  "layer0.inner_margin": [20, 5, 0, 0],
  "layer1.inner_margin": [20, 5, 0, 0]
},

{
  "class": "sidebar_tree",
  "settings": ["theme_sidebar_size_sm"],
  "row_padding": [20, 6, 20, 5]
},

{
  "class": "tree_row",
  "settings": ["theme_sidebar_size_sm"],
  "layer0.inner_margin": [20, 6, 0, 0],
  "layer1.inner_margin": [20, 6, 0, 0]
},

// etc
```

**Comment by Lugoues** [comment]
I'll add new settings for the indent. You are correct, the padding is set as row_padding. I want to make them smaller to better suite the smaller font size.  For example, [20,3,20,3] works very well with the xs size.

**Comment by oivva** [comment]
Oh, I understand) You can add `theme_sidebar_size_xxs` for [20, 3, 20, 3]
