### ISSUE TITLE
Whitespace almost invisible with Boxy Yesterday

### ISSUE THREAD

**Issue by bluebirch** [oivva/boxy#59]
Whitespace is almost invisible with Boxy Yesterday:

![skarmavbild 2016-06-13 kl 11 00 50](https://cloud.githubusercontent.com/assets/4832639/16002149/53496188-3156-11e6-854c-470dbcd52fe1.png)

Compare with Boxy Tomorrow:

![skarmavbild 2016-06-13 kl 11 01 14](https://cloud.githubusercontent.com/assets/4832639/16002150/5349ad82-3156-11e6-936d-2c0da0026808.png)

Or is there some customization variable I have missed?

**Comment by oivva** [comment]
Sorry, it's not possible to add options for color scheme customization. I can make it just a little bit darker in the 2.1.0.

**Comment by oivva** [comment]
Ah, sorry, it seems it's not possible at all. Look at this [thread](https://forum.sublimetext.com/t/scheme-colours-for-line-numbers-and-tab-characters/5029).

Only via very dirty [hack](https://github.com/ckovey/sublime-whitespace-coloring), you can try to do it manually.

**Comment by bluebirch** [comment]
Ouch! Maybe this should be considered a Sublime Text bug/enhancement and reported there?

**Comment by oivva** [comment]
Yes, you can report it [here](https://github.com/SublimeTextIssues/Core/issues). Because this issue shows us that we need ability to change color of the whitespaces.

**Comment by oivva** [comment]
Add comment to the [Known Issues](https://github.com/oivva/boxy/wiki#known-issues) section.
