### ISSUE TITLE
[Yesterday] Arguments are of the same color as functions

### ISSUE THREAD

**Issue by sooqua** [oivva/boxy#73]
I figured out how to fix it:
Install PackageResourceViewer and remove **meta.function-call** in **schemes\Boxy Yesterday.tmTheme**

**Comment by sooqua** [comment]
it's a lot better now tbh. still needs a lot of work tho

**Comment by oivva** [comment]
Can you provide more details?

* Example of code
* Maybe the name of the package that is using for syntax highlighting
* Your suggestions about how it should be look like

**Comment by sooqua** [comment]
Sure
![BEFORE](http://i.imgur.com/tGtGtDz.png)
![AFTER](http://i.imgur.com/EDfQ0Bs.png)

**Comment by michaelblyons** [comment]
1. Broadly speaking, I support this change (and also for Ocean, and other schemes) for UX purposes.
2. It's my understanding that `meta.` scopes aren't _really_ supposed to be used for coloration. They're available for it, yes, but I think they're intended for code analysis and indexing.

Potential downside: other people _may_ be upset by the change, but I suspect that more of them will be relieved than annoyed.

**Comment by oivva** [comment]
@sooqua @michaelblyons Thank you, guys. I'll add this change in 3.0.0.

**Comment by michaelblyons** [comment]
The only change (I think) is to remove `meta.function-call` from [scheme.YAML-tmTheme:70][1] and rebuild.

[1]: https://github.com/oivva/boxy/blob/dev/sources/schemes/scheme.YAML-tmTheme#L70
