### ISSUE TITLE
The selection colour is barely noticeable.

### ISSUE THREAD

**Issue by bensarz** [oivva/boxy#74]
An option to set the selection colour would be much appreciated.
Is there a work around in the meantime?

**Comment by oivva** [comment]
Sorry, it's not possible to add options for color schemes. The selections colour depends on your display characteristics and settings. It's pretty hard to select something universal. But you can change it manually via [Package Resource Viewer](https://github.com/skuroda/PackageResourceViewer).

Look at [this](https://github.com/oivva/boxy/wiki/Settings#advanced) for more info.

**Comment by bensarz** [comment]
Ah! this is perfect! thanks @oivva for getting back to me so quickly!

**Comment by 315234** [comment]
I agree that the selection colour is extremely subtle for the dark schemes, making them unusable for me. Sublime Text ships Monokai with a "bright" version which has a very clear selection colour, would this be possible to do with the dark Boxy schemes at least?

**Comment by oivva** [comment]
@315234 Just update it manually as described [here](https://github.com/oivva/boxy/wiki/Settings#advanced). Selection color depends on your display settings, that's why on some monitors it looks good, on others it looks bad.

**Comment by michaelblyons** [comment]
This is my fault. 🙁 #81
