### ISSUE TITLE
Cannot see highlighting on blocks with BG color

### ISSUE THREAD

**Issue by michaelblyons** [oivva/boxy#81]
You can't see text selections at all when highlighting code blocks in Markdown Extended. They are assigned to the same color. Pretend the final `.` doesn't exist. (I'm having a little trouble nesting markdown with a markdown code block into markdown. 🐤)

```md
Here's some text.

```js
var foo = bar;
// Highlighting in here has no visual indicator at all.
```.
```

**Comment by oivva** [comment]
> You can't see text selections at all when highlighting code blocks in Markdown Extended.

Make it just a little bit better. Other changes users can make manually. I personally use selection color from [this](https://github.com/oivva/boxy/wiki/Settings#advanced).

> Pretend the final . doesn't exist. (I'm having a little trouble nesting markdown with a markdown code block into markdown. :baby_chick:)

I think this is [Markdown Extended](https://github.com/jonschlinkert/sublime-markdown-extended) issue and better to wait for fixing [this](https://github.com/sublimehq/Packages/issues/266).
