### ISSUE TITLE
Text input fields have light background

### ISSUE THREAD

**Issue by sentience** [oivva/boxy#84]
Boxy Ocean theme v2.0.3 on Sublime Text 3 r3117.

![branches__murmur_ _culture_amp_and_settings_ _oivva_boxy_wiki](https://cloud.githubusercontent.com/assets/89772/16367521/b1a02016-3c67-11e6-91b6-6185a3e9d810.png)

```
	"color_scheme": "Packages/Boxy Theme/schemes/Boxy Ocean.tmTheme",
	"theme": "Boxy Ocean.sublime-theme",
	"theme_accent_blue": true,
	"theme_bar": true,
	"theme_find_panel_close_hidden": true,
	"theme_find_panel_font_lg": true,
	"theme_find_panel_size_lg": true,
	"theme_scrollbar_colored": true,
	"theme_scrollbar_line": true,
	"theme_sidebar_size_sm": true,
	"theme_size_md": true,
	"theme_statusbar_size_md": true,
	"theme_tab_font_xs": true,
	"theme_tab_line_size_lg": true,
	"theme_tab_selected_transparent": true,
	"theme_tab_selected_underlined": true,
```

**Comment by oivva** [comment]
I have no this issue on Sublime Text 3 r3117.

Possible solutions:

1. Try to restart Sublime Text: **`Sublime Text -> Quit`** or to force quit, hold the Option key on your keyboard while you right-click on the app’s Dock icon and you’ll see that “Quit” is now “Force Quit.” Click it to force quit the app.

2. Go to **`Sublime Text -> Preferences -> Browse Packages ...`** and remove `Boxy Theme` directory if it exists, then repeat step 1.

Please, additionally provide console output and list of the installed addons.

**Comment by sentience** [comment]
Restarting Sublime Text did the trick. :)
