### ISSUE TITLE
Tabs do not shrink enough when tab scrolling is disabled.

### ISSUE THREAD

**Issue by tim-west** [oivva/boxy#85]
When tab scrolling is disabled (`"enable_tab_scrolling": false`), the tabs do not continue to shrink on smaller window sizes. The tabs appear to have quite a large min-width in comparison to the default theme. This means the tabs get pushed off the edge of the screen and the only way to access them is to either make the window larger or to use keyboard shortcuts to navigate until you get to the right one.

**Comment by oivva** [comment]
The fix will be available in 3.0.0.
