### ISSUE TITLE
Buttons in Find Panel partially hidden for "Find in Files"

### ISSUE THREAD

**Issue by hoesler** [oivva/boxy#86]
Sublime Text Build: 3114
Mac OS X 10.9.5

![boxyissue](https://cloud.githubusercontent.com/assets/1052770/16414076/dc5bc642-3d35-11e6-91bc-2fd1c41499ab.png)

**Comment by hoesler** [comment]
Found the very easy fix with this help (see "Known issues"):
https://packagecontrol.io/packages/Materialize

**Comment by oivva** [comment]
https://github.com/oivva/boxy/wiki#known-issues :wink:
