### ISSUE TITLE
Sidebar wasted space

### ISSUE THREAD

**Issue by gerardroche** [oivva/boxy#89]
It would be nice to have an option to optimise the space used the sidebar.

Here's an example of what I consider wasted space. 

![sidebar](https://cloud.githubusercontent.com/assets/44148/16575482/73431ca0-4280-11e6-86a2-07b10c3af9ca.png)

The entire left margin is too big.

The "FOLDERS" header is only useful if "show open files" is enabled in the sidebar, otherwise it just takes up space.

**Comment by oivva** [comment]
> It would be nice to have an option to optimise the space used the sidebar.

Starting 3.0.0 you'll be able to change indent size: https://github.com/oivva/boxy/wiki/v3.0.0#sidebar-indent

Also I'll add option to disable indenting of the first level (`FOLDERS` & `OPEN FILES`).

With this options margin will be smaller, that's all I can do.

> The "FOLDERS" header is only useful if "show open files" is enabled in the sidebar, otherwise it just takes up space.

It's sad, but there is no way to hide these headers, we can make them invisible only, but this doesn't resolve the issue.
