### ISSUE TITLE
Collapsing folders tree

### ISSUE THREAD

**Issue by PsiXdev** [oivva/boxy#90]
## Expected Behavior
When I use `ctrl + alt + mouse left click` on folder in left sidebar, I expect that the all folder tree will open / unfold.

## Current Behavior
It does not occur if theme enabled (I use "Boxy Yesterday"). Everything works if the standard theme.

## Your Environment
Boxy Yesterday v2.0.3
Sublime Text 3 r3114
Ubuntu 14.04.4

<sup>P. S. Sorry for my bad english</sup>

**Comment by oivva** [comment]
Thanks for the issue. I'll try to fix it.

**Comment by oivva** [comment]
@PsiXdev Ok, I have some info for you. This is not theme related bug. Maybe you should use `Alt` key only with `Mouse Left` click.

![2](https://cloud.githubusercontent.com/assets/9801624/16612899/17c9651c-4372-11e6-86a0-ad20683c9cc6.gif)

**Comment by PsiXdev** [comment]
Strangely. But with the standard theme ```ctrl + alt + Mouse Left``` is work.
Yes, I change some system configs and ```alt + Mouse Left``` began to work. Thank you.
