### ISSUE TITLE
Color changes in 3.0.0

### ISSUE THREAD

**Issue by ppseprus** [oivva/boxy#93]
Hey there!
TL;DR; This is not a bug/issue, this is a question!
I've been using Boxy Ocean for a while now and I love it!
But with the latest update, the colours have changed.
Is there a way to simply switch them back?
I mean, do I have to fork the repo to get it back or there's a more simple solution...
Thanks in advance!

**Comment by oivva** [comment]
@ppseprus hi! You can just download `Boxy Ocean.tmTheme` from https://github.com/oivva/boxy/tree/v2.0.3/schemes and put it into `Packages\User\Color Schemes`, then activate with:

```json
"color_scheme": "Packages/User/Color Schemes/Boxy Ocean.tmTheme",
```

> I mean, do I have to fork the repo to get it back
Or, yes, do this :wink:

**Comment by ppseprus** [comment]
Yeah! I mean, having the 3.0.0 updates but keeping the colors... : )

**Comment by oivva** [comment]
@ppseprus Can you explain me what exactly colors you don't like in 3.0.0? Maybe I'll review them in the next release :wink:

**Comment by ppseprus** [comment]
Sure! So.. a few days ago, the background color of the editor window was the same as the e.g. side bar background. Also, the cursor was blinking yellow. Or... did I miss something?! : P

**Comment by oivva** [comment]
Ah, I understand. I think you was using Boxy UI theme with some of the Material Color Schemes.

**Comment by ppseprus** [comment]
Was I? Could you point me to the exact direction? And sorry my confusion!

**Comment by oivva** [comment]
Sorry, my mistake. Try to install similar schemes, but there's no one that fits your needs. But all that I can say the background color of the editor window wasn't the same as the side bar background.

**Comment by ppseprus** [comment]
Hey!
So.. I checked out everything. It's been a long time since I last touched the look of my Sublime..
I managed to put together these:

	"color_scheme": "Packages/Boxy Theme/schemes/Boxy Ocean.tmTheme",
	"theme": "Boxy Ocean.sublime-theme",
	"theme_accent_cyan": true,
	"theme_size_md": true,
	"theme_tab_rounded": true,
	"theme_tab_selected_filled": false,
	"theme_tab_selected_underlined": true,
	"theme_tab_selected_transparent": true,
	"theme_tab_arrows_hidden": true,
	"theme_button_rounded": true,
	"theme_sidebar_indent_top_level_disabled": true,

But I still could not manage to get the exact same look...
The background and the status bar had the same colour as the side bar. Also the icons were different!

I have a screenshot! : )

![image](https://cloud.githubusercontent.com/assets/1323285/16745448/289fa516-47b6-11e6-9e33-c6e1bee56245.png)

**Comment by ppseprus** [comment]
I loved it! :D
