### ISSUE TITLE
"Replace" row is missing from "Find in Files" panel.

### ISSUE THREAD

**Issue by randy3k** [oivva/boxy#94]
I am using these settings

```json
	"color_scheme": "Packages/Boxy Theme/schemes/Boxy Yesterday.tmTheme",
	"theme": "Boxy Yesterday.sublime-theme",
	"theme_accent_purple": true,
	"theme_bar": true,
	"theme_find_panel_close_hidden": true,
	"theme_size_md": true,
	"theme_tab_line_size_lg": true,
	"theme_tab_selected_transparent": true,
	"theme_tab_selected_underlined": true,
```

<img width="970" alt="screen shot 2016-07-11 at 1 51 19 am" src="https://cloud.githubusercontent.com/assets/1690993/16721095/98a3ac7e-470a-11e6-8578-63cb39fb62c2.png">

The "Find in Files" panel is shown in the above picture, but the third row "Replace" is missing.

Boxy 3.0.0
Sublime 3114
Mac 10.11

**Comment by oivva** [comment]
Please, look at this: https://github.com/oivva/boxy/wiki#known-issues

Just drag `Find & Replace` panel.

**Comment by randy3k** [comment]
Oh, it was the easier fix ever (and shame on me for not trying to resize the panel).
