### ISSUE TITLE
Add theme configurator

### ISSUE THREAD

**Issue by oivva** [oivva/boxy#97]
More details [here](https://forum.sublimetext.com/t/boxy-3-0-0-the-most-hackable-theme-for-sublime-text-3/20564/31)

**Comment by michaelblyons** [comment]
I can't figure out the context under which this works.

**Comment by oivva** [comment]
The theme configurator is a simple plugin that allows us to manipulate all available options via popup. You can run it from the Context Menu, Command Palette and via shortcut (<kbd>WIN + \`</kbd> or <kbd>⌘ + \`</kbd>).
I'll create a getting started video, when 3.2.0 will be released.

For now, look at this :wink: 

![demo](https://cloud.githubusercontent.com/assets/9801624/17428015/dd3281e8-5aed-11e6-891d-b5f56a27d235.gif)

**Comment by michaelblyons** [comment]
Ah. The "Configuration" and "Documentation" options are greyed-out in the right-click menu and did not appear in the Command Palette. When I posted earlier, I thought it was because I had to have a particular file open, but maybe it needs ST v3119+?

This is awesome.

**Comment by oivva** [comment]
Can you show your console output? I think you need satisfy dependencies via PC.

**Comment by michaelblyons** [comment]
I am not sure how I can show console output for options I can't select, but here's the "Environment" output:

- Boxy Theme: 3.1.1
- Sublime Text: 3114
- Platform: osx
- Package Control: False
- Dependencies:
	* mdpopups: 1.9.3
	* markdown: 2.6.6
	* pygments: 2.1a0
	* jinja2: 2.8

My checkout is currently at 4ac18dd

**Comment by oivva** [comment]
> satisfy dependencies
Everything is ok with dependencies

> console output
Can you see any errors in the console? (Menu item `View` -> `Show Console`)

In addition you need to put cursor in the active view (empty or selected opened file)

**Comment by facelessuser** [comment]
Do you think a theme needs a place in the context menu?  I usually think of the context menu as a place for stuff that applies to the view or references the view or content in the view.   I think the command palette and/or the main menu makes sense, but I do question the context menu.  Once people are finally done tweaking the theme, they probably won't need to see it every time they right click.  I think the command palette is actually readily accessible but out of the way enough.

Anyways, the tweaks to the config look good!

**Comment by oivva** [comment]
@facelessuser I agree with you. Don't think about that :disappointed: Will remove it from there.

**Comment by facelessuser** [comment]
> In addition you need to put cursor in the active view (empty or selected opened file)

If you need to, you can check if the cursor is in the viewable region, and if not, popup it up at the first visible point...though since you can scroll well past the last viewable point, I wonder what would happen then?  I guess in that case you really can't show anything...meh.

**Comment by michaelblyons** [comment]
This is probably the console output from around the time I did "Satisfy Dependencies." Nothing else appears to be relevant to Boxy (though I may have missed something&mdash;I use OmniSharp which dumps a _lot_ of source code into the console).

```
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED False

reloading plugin Boxy Theme.boxy_changelog
reloading plugin Boxy Theme.boxy_config
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/michael/Library/Application Support/Sublime Text 3/Packages/Boxy Theme/boxy_config.py", line 9, in <module>
    import mdpopups
ImportError: No module named 'mdpopups'
reloading plugin Boxy Theme.boxy_environment
reloading plugin Boxy Theme.boxy_links
generating syntax summary
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED False
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED False
Package Control: The dependency markupsafe is not currently installed; installing
Package Control: The dependency markupsafe has successfully been installed or updated
Package Control: The dependency mdpopups is not currently installed; installing
Package Control: The dependency mdpopups has successfully been installed or updated
Package Control: The dependency pygments is not currently installed; installing
Package Control: The dependency pygments has successfully been installed or updated
Package Control: The dependency python-jinja2 is not currently installed; installing
Package Control: The dependency python-jinja2 has successfully been installed or updated
Package Control: The dependency python-markdown is not currently installed; installing
Package Control: The dependency python-markdown has successfully been installed or updated
Package Control: All dependencies have been satisfied
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED False
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED False
```

**Comment by michaelblyons** [comment]
Update: pulled 9f058bd and now it's working.

**Comment by facelessuser** [comment]
Remember to restart after running satisfy dependencies.  PC may update things, but the already loaded plugins won't see it until they are reloaded.
