### ISSUE TITLE
Tab rounding and separators not visible enough

### ISSUE THREAD

**Issue by keith-hall** [oivva/boxy#99]
#### Expected Behavior

    "theme_tab_rounded": true,

should make the tabs visibly more rounded

    "theme_tab_separator": true,

should make the tabs more visibly separated

#### Current Behavior

a 1px difference doesn't really count IMO ;)

with `"theme_tab_rounded": true, "theme_tab_separator": true,`:

![boxy rounding](https://cloud.githubusercontent.com/assets/11882719/17096492/515e48fc-5262-11e6-831f-bc462cd4cada.png)

without:

![boxy not rounded](https://cloud.githubusercontent.com/assets/11882719/17096549/8db4ca60-5262-11e6-8dfa-66dfb7236f80.png)

#### Steps to Reproduce

0. Install Boxy Theme from Package Control
0. Change color scheme and theme to `Boxy Monokai`
0. Note how the tab bar looks
0. In user preferences, set `"theme_tab_rounded": true, "theme_tab_separator": true,`
0. Notice how there is barely any difference between how the tab bar looks now and how it looked before...

#### Context

It isn't easy to see where one tab begins and another ends.

#### Your Environment

* Version used: Boxy Monokai 3.10
* Environment name and version: Sublime Text 3 r3118 x64
* Operating System and version: Windows 7 x64

**Comment by oivva** [comment]
Rounded tabs looks good with the one of these options, I'll make `theme_bar_margin_top_sm` by default, when `theme_tab_rounded: true`  starting next version. 

```js
// Increase top margin of the tabs and sidebar to small
"theme_bar_margin_top_sm": true,

// Increase top margin of the tabs and sidebar to medium
"theme_bar_margin_top_md": true,

// Increase top margin of the tabs and sidebar to large
"theme_bar_margin_top_lg": true,
```

> should make the tabs more visibly separated

Ok, I'll play with it :wink:

**Comment by keith-hall** [comment]
Thanks :) awesome issue template BTW!
